spring:
  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL驱动，无需修改
    url: jdbc:mysql://192.168.129.133:3306/express?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root # 数据库连接名
    password: 123456 # 数据库连接密码
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
  # Redis 配置
  redis:
    host: 192.168.129.133 # Redis地址，本地为127.0.0.1
    port: 6379 # Redis端口号，默认为6379
    password: 123456 # Redis密码，没有请保持为空
    timeout: 60000ms
    lettuce:
      pool:
        max-active: 10 # 最大连接数
        max-idle: 5 # 最大空闲连接 默认8
        min-idle: 2 # 最小空闲连接
        max-wait: -1ms # 最大连接阻塞等待时间 默认-1
  thymeleaf:
    cache: false
  application:
    name: express

# 日志配置
logging.file: logs/${spring.application.name}.log
logging:
  file:
    max-size: 10MB
    max-history: 20
  level:
    org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices: debug
#    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}) %replace(%caller{1}){'\t|Caller.{1}0|\r\n', ''} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"


# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.express.domain.bean
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  type-enums-package: com.example.express.domain.enums
  # SQL 执行log，调试时可打开
  configuration:
    cacheEnabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 项目配置
project:
  # 腾讯云短信验证码配置
  sms:
    # 应用 SDK AppID
    app-id: 1400274431
    # 应用 App Key
    app-key: 3fddda3db61f49ae02bd9c7de3dc56aa
    # 短信正文ID
    template-id: 448386
    # 短信签名
    sign: chen学习
    # 短信发送分钟间隔
    interval-min: 1
    # 短信有效分钟
    valid-min: 5
  # 支付宝支付
  alipay:
    # 商户UID
    uid: 2088102179254465
    # APPID
    app-id: 2016101200669795
    # 加密算法
    sign-type: RSA2
    # 支付宝网关
    gateway-url: https://openapi.alipaydev.com/gateway.do
    # 商户私钥，使用密钥生成工具得到
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDdLVoztaKTu38dv+t6VHRIWcF7ZsC+S0Ww5i2kPzKsCc2UH2odneoeAOWrfqHxXJ4wGIt6nbF2gkM7541sUjVa7MwrHjjbFgj42Ps7Zgk+eRgSERs45XmZnOW4Q8cnTmxOLwF+oDV1g+uCTIyAgd/j1a4JrR5csayOrnxcLXZYsTBHTmxwE9ZpHd3mLuspa17f4OdiAqePv4DFiHAbC00C8gKk2MBuVLwmWpCAImYSRMup9aDJB07SzZKtPnEjVXBhI7purAOJ9d6bQHs67wmZOcYjqInU0oWSVyxH0ondxQ7ULhqygOI6c96oj6Lpt6eTF3k1aCNI2ImzXOS3sj3xAgMBAAECggEAPoP/JvaECXXJrEL+8AjHBVw5UAPvHtpvzFyDMhWa4P20WdW3TL/B2NEwGZUleO9Q1w9Y/UNtUa3oCxqb4q4p3pVn8BgOwf4scwoBmPxySHI514F2TFKwWDb8x2SA+h80hbTLm1r1QU4UVzQD0p7jBab0FlAUcObXe0zeYb+H3/FOog307hYT6yIBvHWZcbjErvXLNHvd/qzdU46UhFmYyoeyoe2prE+mcTJria262BVdknj2aoOgP6jhamc1pwhU0Eg7QHEB8LnmfhpGQnQ9rqW5R/hfbAsgpjH4xe66kq1vDU2tm4g2VMMbvtNJJmXk7GOdLLLQ6ERqXfQIk4Nl8QKBgQD5+p0J/Q2TPPb+p9fA0f1yJpqRiU6lDxdWy2F5L2PIrKtyvDChkmjRBGEH+03Ig663xAMslbK4BEL/18zlMZXXyMQL5chZP5kW0UkeisG8yShKvVjOyoGcvs+nCepUcw6G1xoky9lImrmLW0zcT5uYmj7pBNP0qXJy5dstvS9bDwKBgQDigSUndyD9crejLP3q8fXvRTVjzP8n5Elb/9joni2qM6nwWWxQQHT5U++Ee2pcW3MePN3u0WbnW+5WpOY9v3jI9NeW+e6+VUE06TBLipuGmGjvdqa/yeFKUj/WSHjse8tZBLJL5j4Zzc+oBM15BXnSdu5ur5yP+5ZBqsIGehjW/wKBgQCcS6WEaUPjm2qTLj4nwSPGC3z5IfCaIyVkjyUSsB6jidJommGNpA0FIsfIRcgMZskG/Pc/GRn1FDUP4c2qP6aAlHZ/OdxacPk22wPspLUdZGhc0qaEJPmFF4id2AU7Z/TdOgCOoSXpz1PTXfJgjSWr9EUBTJN5lbiJPk4b+v1w4QKBgDE9T/1nWWWflapEcqKrnQI58mRSwTlD2GrGkLnpARZaCtx0JCbCDGvTQmNzjOis/LabFsf+/7bV9lchm+fagwB0sZVhmfQIhpdhBh218R9ubIl6Kr/QvEgy3yvPL3KBavBcJAJ5+BAV/MmS2bQwa45ESosHZCqsz7pQy8MqsdGzAoGBAMOYC/XQ9GGfpXv4GVz4zs20HZTOWhNnx4wz1h25YH/Ymo590PVZs65QhFkA5QH0TrYyUKdpVx3X34Wzgz+XAn80kQbvtgqZxwzFZN3cIrzQyZSP8XM09i4D0mr2PKI2NjLrUlqfsldn0EMJdDw5SQ9lnXCyP97XkBtISBIaqZlL
    # 支付宝公钥
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk6ITEWXX0Kb+sOHy2cR5qQ/bXGDLVcoQqkISap/Xu/cTofcgbWp21/Fo4Iq4xNaEsuEnfpOA9odIN3TiBS0pbzC+yfkMN27eIpJEpc/VylfrzVe0PBqK1Kb3W0RSuF4p/PsuGLjKYK7HPrOiLGGOjWtuambmWJ4L+bHSAySy0TR8LDK9uoRc4HCefmSwTlvz2Vt55TTL4n7U4WdsWzoZRKiwK0SIpFvu4TAE1zKBM5ozgISwSZA4+3oCQmH7OJeOrLlFgMhjSEUFQg3oDQdz79e5tQbtiEK+tdztBn3X1cvbwQYw7UFc+wZWX1w48j9ed7sWyuCHboUCbZtwfOBqzQIDAQAB
    notify-url: ${server.addr}/order/alipay/notify # 支付异步通知URL，需公网能够访问
    return-url: ${server.addr}/order/alipay/return # 同步通知URL，无需公网访问
  # 百度人脸识别
  baidu:
    aip:
      # 应用 APPID
      app-id: 17565026
      # 应用API KEY
      app-key: PNqLm2TjvWQiGhYwrGN1G08X
      # 应用 Secret Key
      secret-key: WbsZhASOKx9TNvGbMC97YpHFFW1UBe0O
      # 连接超时ms，默认 2000
      conn-timeout: 2000
      # socket超时ms，默认60000
      socket-timeout: 60000
      # 最低被接受的人脸置信分数[1,100]，分数越高，要求越严格，也越准确。
      accept-score: 90
  # 三方登陆配置
  third-login:
    qq:
      app-id: 101568611
      app-key: 2a3716583b2355aeab442f1949c9f6e1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 服务启动
server:
  port: 8010
  # 公网暴露 IP
  addr: http://127.0.0.1:${server.port}
  max-http-header-size: 8192
